import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const root=new URL('../',import.meta.url);
const briefs=JSON.parse(readFileSync(new URL('eval/briefs.json',root),'utf8'));
const escape=text=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const completed=briefs.filter(({cycle})=>existsSync(new URL(`eval/cycles/${cycle}/outcome.md`,root)));
const rows=completed.map(({cycle,task,artifact,kind,reviewMode})=>`<li><span class="cycle">${cycle}</span><div><h2><a href="${escape(artifact ?? (kind==='tooling' ? `cycles/${cycle}/outcome.md` : `cycles/${cycle}/index.html`))}">${escape(task.split(' with ')[0].replace(/\.$/,''))}</a></h2><p class="muted">${escape(task)} ${reviewMode==='self'?'Self-review.':'Independent review.'}</p><a class="meta" href="cycles/${cycle}/outcome.md">Read the outcome</a></div></li>`).join('\n');
writeFileSync(new URL('eval/index.html',root),`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Design taste experiments</title><link rel="stylesheet" href="../skills/editorial-calm/assets/tokens.css"><link rel="stylesheet" href="../skills/editorial-calm/assets/fonts.css"><style>
*{box-sizing:border-box}body{margin:0;background:var(--background);color:var(--foreground);font:var(--type-weightBody) var(--type-bodyWeb)/var(--type-lineHeight) Inter,system-ui,sans-serif}main{max-width:896px;margin:auto;padding:24px var(--space-gutterWeb) 64px}header{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px;border-bottom:1px solid var(--border);padding-bottom:24px}button{font:inherit;border:1px solid var(--input);border-radius:var(--radius-control);color:var(--foreground);background:var(--background);min-height:44px;padding:8px 14px;cursor:pointer}h1{font-size:var(--type-pageTitle);font-weight:var(--type-weightTitle);letter-spacing:-.03em;line-height:1.2;margin-top:40px;overflow-wrap:anywhere}h2{font-size:var(--type-rowTitle);font-weight:var(--type-weightTitle);margin:0}p{max-width:65ch;margin:8px 0}.muted,.cycle,.meta{color:var(--muted-foreground)}a{color:inherit;text-underline-offset:4px}.meta{font-size:.875rem}ul{list-style:none;padding:0;margin:32px 0}li{display:grid;grid-template-columns:36px minmax(0,1fr);gap:16px;border-top:1px solid var(--border);padding:24px 0;overflow-wrap:anywhere}.cycle{font-variant-numeric:tabular-nums}:focus-visible{outline:2px solid var(--ring);outline-offset:4px}
</style></head><body><main><header><span>Flavius design taste</span><button id="theme" aria-pressed="false">Dark theme</button></header><h1>Experiments with the taste</h1><p class="muted">Working screens and verification experiments, with recorded evidence and corrections. Each outcome identifies its review method. ${completed.length} cycles have completed review.</p><ul>${rows}</ul></main><script>const button=document.querySelector('#theme');let dark=matchMedia('(prefers-color-scheme: dark)').matches;function render(){document.documentElement.classList.toggle('dark',dark);button.setAttribute('aria-pressed',String(dark));button.textContent=dark?'Light theme':'Dark theme'}render();button.addEventListener('click',()=>{dark=!dark;render()});</script></body></html>\n`);
console.log(`Generated gallery for ${completed.length} reviewed cycles.`);
